code review of java-racingcar-implement
kth496/java-racingcar-implement pull request #1
Opened 2022-03-12 16:01 UTC by ShinjaeKwon

### 구현 기능 
구현 기능은 자동차 생성 기능, 게임 로직 기능, 에러 처리 기능, 전진 기능, 사용자 입력 기능, 출력 기능, 우승자 판단 기능으로 나눴습니다.
### 자동차 생성 기능
`Car`에 구현되어 있는 `createAsManyCars`를 통해 자동차들을 `ArrayList`로 생성합니다.
처음에는 `Array`로 구현하였으나 후에 공동 우승자 판단 로직을 편리하게 사용하기위해 `ArrayList`로 리팩토링하였습니다. 기존 `StringTokenizer`의 토큰의 갯수를 세주는 방식으로 자동차의 갯수를 세주고, 그에 따라 `Array`를 만들었는데 `ArrayList`를 사용함으로써 불필요한 코드를 지우게 되었습니다.
### 게임 로직 기능
`inputOfAttempts`를 통해 게임 진행 횟수를 입력받고, 횟수만큼 게임 진행 기능인 `progressGame`을 반복하였습니다.
### 에러 처리 기능
에러처리는 5글자 초과, 시도할 횟수가 숫자가 아닐 때의 2가지 상황을 `ExceptionHandler`를 통해 에러처리를 하였습니다.
사용자가 실패한 이유를 알 수 있도록 메시지를 작성하였습니다.
###전진 기능
`Car`에 구현하였으며 `RandomNumber`의 `makeRandomNumber`메서드를 통해 사용자가 설정한 기준숫자를 넘기면  `forward`메서드를 실행시키도록 작성하였습니다.
### 사용자 입력 기능
프로젝트 내 모든 입력기능을 넣었고, 입력값을 `FormChecking`내부에 있는 메서드들로 올바른 값인지 검사하여 정확한 값만 입력되도록 구현하였습니다.
### 출력 기능
프로젝트 내 모든 출력 기능을 넣었습니다. 
### 우승자 판단 기능
`JudgementWinner`에 구현하였고, `getHighPosition`메서드를 통해 최고값을 알아내, `removeLoser`함수를 통해 `ArrayList`를 돌면서 최고값과 다르면 `ArrayList`에서 삭제하는 방식을 사용하였습니다.
후에 단독 우승과 공동 우승을 `ArrayList`의 size로 판단하여 다른 출력을 하도록 구현하였습니다.

## 질문
1. 어느 순간에 `static import`를 사용해야 하는지 잘 모르겠습니다. `static`이라 남발하면 단점이 있을거 같아 질문드립니다.
2. 저번 피드백 때 `for`문 등 내부에서 사용하는 `0`,`1`등 같은 숫자들도 하드코딩하지 말라고 하신걸로 기억하는데, 일단 상수로 구현은 하였지만 관련이 없는 클래스에서 상수를 끌어오는 거같아 질문드립니다. 따로 상수 숫자만 구현되어있는 클래스를 구현하여 참조하는 방법도 괜찮은지 궁금합니다.

2022-03-12 18:33 UTC, kth496 requested changes
고생많으셨습니다! 질문해주신 부분은 코드리뷰 코멘트에 남겨놨으니 확인해주세요~ 추가로 3번 질문에 대해 답변드립니다.

> PR작성을 저번에는 commit 기준으로 어떤걸 구현하였는지 설명하였는데, 이렇게 기능별로 어떻게 구현했는지 코드 리뷰 형식으로 작성해도 되는지 궁금합니다.

넵 기능별로 어떻게 구현했는지 설명해주셔도 상관없습니다. 근데 지금 작성해주신 내용은 사실 별 도움이 되지 않습니다. 어차피 코드를 보면 알 수 있는 내용만 적혀있거든요. 핵심 로직은 결국 코드가 기준이 되기 때문이죠. PR은 부수적인 참고 자료일 뿐입니다. 따라서 처음부터 코드를 읽기 좋게 짜는 것이 중요하구요. PR에는 구현을 왜 이렇게 했는지에 대한 근거를 적어주시는게 좋아보입니다.

예를 들면 지금 `Array`를 `ArrayList`로 변경하신 코멘트가 적혀있는데, 이 부분에서 어떤 어려움때문에 전환하게 되었는지에 대한 근거 정도가 되겠네요! 나머지 내용들은 메서드나 클래스명을 제거하시고 기능 명세 `README`파일에 적으면 더 좋을 내용이라고 생각합니다.

2022-03-12 18:33 UTC, kth496 commented on src/main/java/racingcar/handler/ExceptionHandler.java
> +
저번에 피드백드린 [코멘트](https://github.com/kth496/java-baseball-implement/pull/1#discussion_r820937744) 이후로 모든 클래스에 `Handler`를 붙이고 계신데요. 
 `ExceptionHandler`는 예외를 받아서 처리하는 느낌이 강하므로, 약간 애매하다고 말씀드렸던 기억이 납니다. 지금의 구조를 보면 더욱 그런 어색함이 강하죠. `FormChecking`클래스의 31번 라인에서 `try`구문 안에서 `ExceptionHandler`클래스를 사용하는데 어색하지 않나요? 마치 `catch`에 있어야 더 좋은 이름 같아 보이네요. Handler는 받아서 처리한다는 맥락에서 사용해보세요.

2022-03-12 18:33 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +	}
생성자를 내부에서만 사용하고, 외부에는 정적 팩토리 메서드를 제공한다면 생성자를 `private`으로 만들어주세요. 지금은 생성자를 직접 사용해서 이름 길이 체크를 회피할 수 있습니다.

아울러, 지금 만들어진 `createCar` `createAsManyCars`메서드도 `Car`클래스 내부에서만 사용되네요. 이러한 메서드들은 모두 `private`으로 만들어주세요.

2022-03-12 18:33 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +		return carsNamesList;
한 줄로 작성이 가능합니다!

2022-03-12 18:33 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +	}
이러한 부분이 바로 `static`메서드로 만들면 안되는 전형적인 케이스입니다. 이 메서드가 사용되는 `GameLogic` 클래스를 살펴보세요. 코드를 다음과 같이 사용하고 있습니다.

```java
Car.forward(carsNamesList.get(car));
```

자동차 클래스를 향해서, 같은 클래스의 인스턴스를 인자로 전달하고 있습니다. 어색하지 않으신가요? 저라면 `currentCar.moveForward()`처럼 작성했을 것입니다. 왜냐하면 자동차가 전진하는 것은 자동차 스스로 할 수 있는 일이고, 자바 세계에서는 이를 객체에 메시지를 보내서 해결할 수 있기 때문이죠. 다시말해 `currentCar`라는 객체에 `moveForward`라는 메시지를 보내서 움직이게 한 것입니다. `static`으로 만들어질 이유가 없지요. 

지금 재권님은 `static`메서드를 과하게 많이 사용하고 계십니다. 방금 말씀드린 측면에서 `static`이 필요한 상황인지 고민해보시면 좋을 것 같아요.

비슷한 이유로 사실 `static import`를 할 일도 많지 않습니다. 굳이 `static`으로 만들 이유가 없으니까요. `static import`를 하는 순간 앞에 붙는 클래스명이 사라지므로 메서드명만 가지고 의미를 유추해야 합니다. 따라서 문맥이 섞이지 않는 상황에서만 사용해야하지요. 다시말해 어떤 메서드의 이름만 보고도 의미가 이해되면서, 클래스명이 별다른 정보를 제공하지 않는다면 `static import`를 고려해볼 수 있겠습니다. 1번 질문의 답변이 되었기를 바랍니다 😃

2022-03-13 01:42 UTC, ShinjaeKwon commented on src/main/java/racingcar/GameLogic.java
> +		printRacingResult(carsNamesList);
`for`문에서 `for-each`문법으로 바꿧습니다.

2022-03-13 01:43 UTC, ShinjaeKwon commented on src/main/java/racingcar/handler/UserInputHandler.java
> +	}
처음에 메서드 별로 기능을 분리하려고 하다가 이렇게 한것같습니다. 
`input()`메서드 제거하고 `readLine()`메서드 한개만 사용하였습니다.

2022-03-13 01:44 UTC, ShinjaeKwon commented on src/main/java/racingcar/handler/UserInputHandler.java
> +		return inputOfAttempts(input());
`input` 변수명을 명확하게 `inputNumber`로 바꿧고, `input()`메서드는 제거하였습니다.

2022-03-13 01:44 UTC, ShinjaeKwon commented on src/main/java/racingcar/handler/UserInputHandler.java
> +	}
둘은 완전히 똑같은 기능이라 하나로 통일해줬습니다.

2022-03-13 01:45 UTC, ShinjaeKwon commented on src/main/java/racingcar/handler/ExceptionHandler.java
> +
`ExceptionHandler`를 `InputException`으로 변경하였습니다.

2022-03-13 02:15 UTC, ShinjaeKwon commented on src/main/java/racingcar/Car.java
> +	}
넵 내부에서만 사용하는 클래스들은 `privaet`으로 선언하였습니다.

2022-03-13 02:15 UTC, ShinjaeKwon commented on src/main/java/racingcar/Car.java
> +		return carsNamesList;
바로 `Car.createAsManyCars()`를 반환하도록 인라인화 하였습니다.

2022-03-13 02:17 UTC, ShinjaeKwon commented on src/main/java/racingcar/Car.java
> +	}
메서드 명으로 의미가 유추가 가능하면 `static import`를 고려해보겠습니다. 
입력 함수인 `readLine()`을 제외한 `static import`는 모두 제거하였습니다.
질문 답변 감사합니다. 명확하게 이해하였습니다.

2022-03-13 02:18 UTC, ShinjaeKwon commented on src/main/java/racingcar/GameLogic.java
> +	public static final int NUMBER_ONE = 1;
의미없는 상수들은 일단 제거하였고, 공통적인 의미가 있는 곳은 다시 찾아보겠습니다.

2022-03-13 03:50 UTC, ShinjaeKwon commented on src/main/java/racingcar/check/FormChecking.java
> +		return true;
`Integer`클래스에 함수를 따로 찾아봐도 뭔지 잘 모르겠습니다.
일단은 `parseInt()`메서드로 `try-catch` 방식으로 값을 `return`하게 리팩터링 하였습니다.

2022-03-13 14:09 UTC, ShinjaeKwon commented on src/main/java/racingcar/GameLogic.java
> +		JudgementWinner.judgeWinner(carsNamesList);
`printResult()`메서드를 `printGameStart()`로 이름을 변경해 게임 시작을 알리는 의미가 더 명확하게 전달되도록 했습니다.

2022-03-13 14:11 UTC, ShinjaeKwon commented on src/main/java/racingcar/check/NumberChecking.java
> +		return false;
넵 조건문을 `return`하게 해서 인라인화 하였습니다.

2022-03-14 10:20 UTC, ShinjaeKwon commented on src/main/java/racingcar/JudgementWinner.java
> +		PrintHandler.printCoWinner(carsNamesList);
`join`메서드를 활용하여 구분없이 출력하도록 변경하였습니다.

2022-03-14 10:23 UTC, ShinjaeKwon commented on src/main/java/racingcar/check/FormChecking.java
> +				return false;
`catch`에서 모두 처리하도록 변경하였습니다.

2022-03-18 02:18 UTC, closed without merging