java-racingcar-implement
kth496/java-racingcar-implement pull request #2
Opened 2022-03-16 21:17 UTC by eunbii0213

<힘들었던 점>
'메세지 출력 후' 입력을 다시 받으라는 말이 에러메세지를 sout으로 출력하라는 뜻이 아닌 저번 과제처럼 e.printStackTrace()를 해야하는 걸로 이해해서 많이 헤맸습니다....😭 

<고민했던 점>
1. 자동차 이름을 입력 받을 때 "ㅏ", "ㄱ", "0"같은 이름도 가능한지 적혀있지 않아서 일단 가능하게 구현했습니다.
2. 유저의 인풋값의 범위가 정해져있지 않아 n값이 0도 가능하다는 가정하여 구현했습니다.

<질문사항>
1. Checker.class에서 코드 효율이 너무 좋지 않아보입니다. 저번과 마찬가지로 stackoverflow가 발생할 수 있는 구조라고 생각합니다. 어떤 방향으로 수정을 해야할까요?? 선생님의 생각이 궁금합니다!
2. 코드에 구현한 forEach문들은 처음에 for문으로 작성했다가 IntelliJ option+enter 기능으로 forEach로 바꾼 것인데 괜찮을까요? 역시 아직은 배우는 단계이니 하나하나 만들어보는 게 좋을까요?
3. 저번 피드백 때 private 변수는 가능한 getter와 setter를 만드는 게 좋지 않다고 말씀하신 게 기억이 납니다. 그래서 이 부분을 수정하고 싶은데 방법이 잘 떠오르지 않습니다.😭 Car.class에서 getName()을 사용하지 않고도 name을 Application.java에서 받을 수 있는 방법이 있을까요?

2022-03-18 13:21 UTC, kth496 commented
@eunbii0213 이번 미션도 고생하셨습니다! 고민하고 구현하신 흔적이 많이 보이네요. 일단은 고민한 부분과 질문사항에 대해 답변드립니다!

> 자동차 이름을 입력 받을 때 "ㅏ", "ㄱ", "0"같은 이름도 가능한지 적혀있지 않아서 일단 가능하게 구현했습니다.

좋습니다!! 따로 요구사항이 없다면 임의로 설정하거나, 모두 받으면 됩니다.

<br>

> 유저의 인풋값의 범위가 정해져있지 않아 n값이 0도 가능하다는 가정하여 구현했습니다.

위 답변과 동일합니다!

<br>

> Checker.class에서 코드 효율이 너무 좋지 않아보입니다. 저번과 마찬가지로 stackoverflow가 발생할 수 있는 구조라고 생각합니다. 어떤 방향으로 수정을 해야할까요?? 선생님의 생각이 궁금합니다!

지금은 잘 구현하신 것 같아요! 저번에는 재귀함수이기 때문에 문제가 될 것이라 말씀드렸던 것으로 기억합니다. 왜냐하면 재귀함수는 매번 함수 스택이 다시 쌓이니까 언젠가 터질 수 있기 때문이지요! while문으로 구현하면 `busy-waiting`이라 하는 구현방법이므로 그리 효율적이지는 않지만, 스택 오버플로우가 나지는 않을겁니다.

자세한 내용은 [busy waiting(바쁜 대기)](https://ko.wikipedia.org/wiki/%EB%B0%94%EC%81%9C_%EB%8C%80%EA%B8%B0)을 참고해보세요!

<br>

> 코드에 구현한 foEach문들은 처음에 for문으로 작성했다가 IntelliJ option+enter 기능으로 forEach로 바꾼 것인데 괜찮을까요? 역시 아직은 배우는 단계이니 하나하나 만들어보는 게 좋을까요?

아닙니다! IDE의 기능은 최대치로 활용하시도록 연습하세요! 우리의 개발은 종이에 손으로 쓰는 방식이 절대 아닙니다. IDE는 개발을 도와주는 도구니까 도구를 잘 쓰는 것도 능력입니다 ㅎㅎ 특히 `option+enter`는 막강한 리팩터링 기능이므로 반드시 활용하셔야합니다. 아주 잘하신 부분입니다 👍

<br>

> 저번 피드백 때 private 변수는 가능한 getter와 setter를 만드는 게 좋지 않다고 말씀하신 게 기억이 납니다. 그래서 이 부분을 수정하고 싶은데 방법이 잘 떠오르지 않습니다.😭 Car.class에서 getName()을 사용하지 않고도 name을 Application.java에서 받을 수 있는 방법이 있을까요?
잘 기억해주신대로 getter, setter는 최대한 자제하는게 좋습니다. 다만 필요하다면 사용해야겠지요. 지금은 getter가 없이 구현이 불가능하니 잘 사용하신 것 같아요. 무조건 사용이 금지하는게 아니라 최대한 자제하고, 꼭 필요한 곳에만 써야한다는 개념으로 받아들여주세요! (다시말해, 필요하지 않으면 만들지 않는다는 뜻입니다!)

2022-03-18 13:23 UTC, kth496 commented
<img width="668" alt="스크린샷 2022-03-18 오후 10 22 18" src="https://user-images.githubusercontent.com/54257564/159010455-5ce1b843-c67d-4171-b890-2c90cbc2479e.png">

<br>

추가로, 현재 게임을 동작시켜보면 스펙과는 조금 다르게 결과가 나오고 있습니다. 경주의 매 스텝마다 너무 많은 결과가 나오고 있으며, 경주가 제대로 진행이 되지 않는 것 같아요. 또한 우승자도 올바른 목록이 출력되지 않고 있습니다. 문제 요구사항의 입출력을 잘 확인하시고 수정해주세요!

2022-03-18 13:58 UTC, eunbii0213 commented
헉 이런 실수를 하다니!! 😭😭  얼른 수정해보겠습니다!! 알려주셔서 감사합니다!

2022-03-18 14:42 UTC, eunbii0213 commented
선생님! 방금 버그 수정했습니다! 피드백 부탁드립니다!!🙂

2022-03-19 13:52 UTC, kth496 requested changes
고생많으셨습니다! 이번 과제는 전체적으로 조금 복잡하게 구현하셨어요. 피드백 드린 부분을 살펴보시고, 특히 `Checker`클래스의 복잡도를 개선해는 노력을 해보시면 좋을 것 같아요!

또한 `static`을 사용할 곳과 아닐 곳을 잘 생각해보시고, `public`도 모두 `private`으로 변경하시는 방향으로 개선해보세요. 지금은 `public`이 너무 많아서 특정한 속성이나 변수가 어디서 바뀌는지 변경 지점을 파악하기가 어려운 코드가 되었습니다. (상수 제외)

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +    public static ArrayList<String> carName;
`ArrayList`타입으로 직접 쓰기보다는 `List`로 쓰시는 것이 좋습니다! `List`는 인터페이스이기 때문이죠. 자세한 이유에 대해서는 한번 고민해보고 화요일에 이야기 나눠보면 좋을 것 같네요.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Checker.java
> +    }
`tempList.clear();`로 쓰시는게 더 간단하고 성능도 좋습니다!

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +    public static String userNumberInput = "";
모든 변수를 static으로 만드신 이유가 있나요?? 해당 변수들은 선언 시점에 값이 고정되는 것이 아니라, 유저의 입력에 따라 값이 바뀌는데 static으로 선언해두는 것은 의미에 맞지 않아보입니다.

게다가 지금은 상당수의 변수들이 `public`으로 선언되어 있네요. 다시말해, `User`객체의 어떤 멤버 변수가 다른 클래스와 밀접한 연관을 가지게 된다는 뜻입니다. 실제로도 `Checker`에서 마음대로 가져다가 바꾸기도 하고 넣기도 하는 상황입니다. 이것은 매우 좋지 않은 구조에요. 모든 객체는 자기 자신의 멤버 변수를 최대한 감추고, 외부와는 공개된 채널이나 약속된 규칙으로만 소통하며 변화해야 합니다. 지금은 `public`이 많아서 어디서 어떻게 무엇이 변하는지 파악하기가 너무 힘들어요.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +    }
`static`변수는 이렇게 접근하면 안됩니다. 물론 동작은 하겠지만, `User.userInput`으로 쓰는 것이 더 정확한 표현이에요.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +            index++;
인덱스를 사용하셔야한다면 이렇게 작성하시기보다 그냥 평소처럼 `for(int i =0; ...)`으로 작성하시는게 좋습니다. `for-each`문법은 인덱스를 직접 사용하지 않기 때문에 장점이 있는 것인데 지금은 그러한 장점을 살리지 못하고 있어요. 아울러 `carNameStr` 변수도 전혀 쓰이지 않으니 이렇게 작성할 이유가 없습니다.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +    public void carNameListDeepCopyFromOtherList(ArrayList<String> otherList) {
이 메서드가 왜 있는지 잘 모르겠어요. 현재 구조를 살펴보면 `carNameListAdd` 메서드를 이용해서 유저의 인풋을 일단 바로 `carName`에 집어넣고, 나중에 검증이 통과되면 `tempList`와 바꿔치기 하는 것으로 보이는데요. 이렇게 하기보다는 유저의 입력을 먼저 검증하고, 그 후에 리스트에 집어넣으면 두 번 넣거나 카피할 필요가 없을 것 같아요.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +    }
이 부분은 따로 분리할 필요가 없어보입니다. 어차피 쓰이는 곳도 하나의 메서드이니까요! `ArrayList`의 초기화에 쓰이는 부분은 사실 없어도 초기화가 가능하구요.`for`문 반복하는 곳에서는 `size`메서드로 그냥 크기를 봐도 되니까요!

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +        gameNumber = Integer.parseInt(userNumberInput);
`checker.userInputNumberChecker(userNumberInput);`에서 `parseInt`를 이미 하면서 체크까지 끝냈는데, 아래에서 또다시 `parseInt`를 하고 있네요. 중복된 로직은 개선하면 좋을 것 같습니다.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/User.java
> +        return true;
한 줄로 작성 가능해 보입니다.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +    private final String COLON_WITH_BLANK = " : ";
상수가 의도시라면 `static final`로 선언하셔야 합니다.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +    }
이 메서드는 `int`가 아니라 `boolean`을 반환하는 것이 의도상 더 적절해 보입니다. 만약 `compareTo` 메서드를 의식해서 이러한 스타일로 만드신거라면, `Comparable` 인터페이스를 구현하는 방향으로 하시는게 더 적절합니다.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +        return false;
한줄로 축약 가능해 보입니다!

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Car.java
> +        return Randoms.pickNumberInRange(1, 9);
하드코딩된 값은 상수로 분리해주세요.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Application.java
> +            user.decreaseGameNumber();
static 메서드를 호출할때는 `클래스명.메서드명`으로 호출하셔야 합니다. 그리고 `isGameNumberZero`메서드는 이름이 이상하네요. 영어 문장대로 읽어보면 숫자가 0일때 `true`가 나와야 하지만 실제로는 `false`가 나오고 있습니다. `while`문 입장에서도 괄호 안에 있는 조건이 `true`일때 계속 순환한다고 읽어야 하는데 지금은 숫자가 0이면 계속 돌겠다는 의도로 읽혀요.

ex) `User.isGameNumberZero()`

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Application.java
> +        IntStream.range(ZERO, carList.size()).filter(index -> carList.get(index).isBiggerThanPosition(MAX) != -ONE).forEach(index -> MAX = carList.get(index).isBiggerThanPosition(MAX));
이 코드는 스트림을 잘 활용하셨지만 알아보기 너무 힘듭니다. 스트림에서 클래스의 스태틱 변수를 수정하는 상황이므로 무엇이 어떻게 바뀌는 것인지 예측하기가 매우 어렵습니다. `setMAX`로 하시기보다, 이 메서드 자체에서 가장 앞의 차의 포지션을 반환하도록 하시는 게 좋아보입니다.

참고로 같은 일을 하는 `stream`의 `max` api가 이미 존재합니다.

2022-03-19 13:52 UTC, kth496 commented on src/main/java/racingcar/Application.java
> +    }
이 메서드에 여러 피드백이 있습니다.

1. 하드코딩된 값을 상수로 분리하라.
하드코딩된 값을 상수로 분리하라는 것은 단순히 0을 ZERO, 2를 TWO로 분리하라는 의미가 아닙니다. 해당 숫자가 가진 의미에 맞게 이름을 붙여 분리하라는 뜻입니다. 지금 TWO라고 쓰인 부분에서 숫자 2라는 의미 외에 다른 뜻을 찾을 수 있나요? 사실상 숫자 2를 하드코딩한 것과 다를 바 없습니다.

2. 컨벤션
스트림으로 길어지면 적절하게 줄바꿈을 하셔야 합니다. 컨벤션에도 한 라인에 들어갈 수 있는 코드의 양이 정해져있어요.

3. Winner가 한명 vs 여러명
각각의 경우에 콤마가 뒤에 붙는다면 떼어내고, 아니라면 붙이는 형태의 코드는 읽기 어렵습니다. `String.join` 에 대해 알아보세요!

2022-03-19 20:20 UTC, eunbii0213 commented
선생님! 코드 수정했습니다! 
다만... checker class를 어떻게 하면 더 효율적으로 바꿀 수 있을지는 아직도 감이 잘 잡히지 않습니다😭 예외를 던지고 catch하는 method가 나뉘어졌기 때문에 복잡해지는걸까요..
Checker class를 어떤식으로 바꾸면 좋을지 힌트를 받을 수 있을까요..?! 저도 계속 고민해보고있겠습니다!

2022-03-20 12:13 UTC, kth496 commented
@eunbii0213 각 클래스가 많은 일을 담당하다보니 로직이 뭉쳐있는 느낌입니다. 예를 들어 출력하는 문자열은 어떤 경우에 `User`에 있기도 하고 또 다른 멘트는 `Chekcer`에 있기도 하지요. 출력과 관련된 부분은 모두 View 관련 클래스로 분리하는게 좋아보입니다.

또한 불필요한 변수들도 많습니다. `tempList`가 꼭 필요한지 의문이에요. 이름을 통해서 의도를 파악하기도 힘들구요. 
`userNumberInput`과 `userInput`도 멤버 변수로 있어야 하는지 궁금합니다. 클래스 자체가 가져야할 필요가 없다면 메서드끼리 인자로 전달하는 방식이 더 이해하기 쉽습니다. 클래스의 멤버 변수로 들어가는 순간, 클래스의 상태 중 하나가 됩니다. 즉 어떻게 변화하는지 추적해야 하는 대상이 되어버리는 거에요. 지금은 유저의 인풋을 굳이 이렇게 관리할 필요가 없어보이니 개선해보시면 좋을 것 같아요!

추가로 말씀하신 코드 작성은 변경하셔도 무방합니다!

2022-03-21 04:03 UTC, eunbii0213 commented
선생님! 소스코드 수정 완료했습니다!
피드백 부탁드립니다!

2022-03-24 16:10 UTC, kth496 commented
@eunbii0213 코드리뷰는 줌으로 설명드린 내용으로 대신하겠습니다 😃

2022-03-24 16:10 UTC, closed without merging