미션 수행 💫
kth496/java-racingcar-implement pull request #3
Opened 2022-03-25 10:26 UTC by Hepheir

# TODO:

- [ ] README.md 작성하기
- [ ] 궁금했던 것 정리하기

2022-03-25 19:46 UTC, kth496 requested changes
@Hepheir 고생많으셨습니다! 리뷰를 남겼으니 확인해보세요~

아울러 코드 리뷰는 해당 리뷰가 달린 특정 메서드나 클래스 뿐 아니라 전체적으로 적용 가능한 지점을 살펴보시면 좋을 것 같아요! (메서드 참조 등)

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/View.java
> +        String rawUserInput = Console.readLine();
현재 `View`클래스와 `Console`이 결합되어 있습니다. PR 다이어그램상으로도 그렇게 나타나고 있구요. 사실 입출력이 밀접한 연관을 가지지만, 연습차원에서 분리해주는게 좋습니다. 경우에따라 파일 입출력을 활용할수도 있기 때문이죠.

지금의 구조에서는 `Control` 클래스와 같은 포지션에 입출력만 엮어주는 클래스를 새롭게 도입할 수 있을 것 같습니다!

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Control.java
> +        View.getUserInputForCarNames().forEach((name) -> Model.addCar(name));
`View.getUserInputForCarNames().forEach(Model::addCar);`로 작성 가능합니다. 메서드 참조를 활용하면 더 간단해지죠!

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Control.java
> +    };
요기는 오타같네요. 없어도 되는 부분입니다! 코드에 전체적으로 이런 오타들이 있으니 수정해주세요~

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Control.java
> +        Model.setNumberOfTries(View.getUserInputForTries());
View의 결과물을 모델로 전달한다? 어색합니다. 왜냐하면 View에서 Input까지 처리하기 때문이죠. 앞서 말씀드린 부분과 동일한 맥락이고, 분리해보시면 좋을 것 같습니다!

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/View.java
> +    private static Consumer<Object> printFunction = x -> System.out.print(x);
`private static final Consumer<Object> printFunction = System.out::print;` 이렇게 작성 가능합니다!

1. 변경될 가능성이 없으니 `final`로 선언
2. 메서드 참조 문법으로 개선

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Model.java
> +            }
객체에서 값을 꺼내지 말고, 객체에 메시지를 보내는 구조로 바꿔보면 어떨까요?

지금 앞으로 전진하는 것을 setter와 getter를 조합해서 직접 1을 증가시키지 않고, Car에게 메시지를 보내서 스스로 증가하게 제한한 것과 유사한 방향입니다. (이 부분은 이미 잘 해두셨습니다!)

`car.isMaxPosition(maximumDistance);` 와 같은 형태로 작성하는 것이지요! 이렇게 작성하면 `Car`와 관련된 핵심 로직이 도메인 레이어로 내려갑니다. 도메인 객체를 더욱 풍성하게 만들 수 있는 것이지요. 도메인을 풍성하게 만드는 것은 저번에 말씀드린것과 같이 여러 장점들이 있습니다. 한번 시도해보세요!

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Model.java
> +        return names;
`List<Car>`를 `List<String>`으로 변환하는 상황이네요. 다음과 같이 더 간단하게 작성 가능합니다!

```java
public static List<String> getFurthestCarNames() {
    return getFurthestCars().stream()
        .map(Car::getName)
        .collect(Collectors.toList());
}
```

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Model.java
> +    }
`private`으로 되어있는 멤버 스태틱 변수를 `private`접근 제한자의 메서드로 굳이 접근할 필요는 없습니다. 이 클래스 내에서만 사용되는 것이 확실하므로 별도의 액세스 메서드를 작성하지 않아도 괜찮아요.

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/Model.java
> +    }
사용되지 않는 메서드는 제거해주세요!

2022-03-25 19:46 UTC, kth496 commented on src/main/java/racingcar/View.java
> +        List<String> names;
names 변수 없이 작성가능한 상황이므로 없애도 될 듯 합니다!

2022-03-26 01:22 UTC, Hepheir reviewed
피드백 적용했습니다!

PR 다이어그램을 다시 그려봤습니다.

![image](https://user-images.githubusercontent.com/19310326/160219131-f4b18605-3db2-407a-b99f-53e73ea2216c.png)

2022-03-26 01:22 UTC, Hepheir commented on src/main/java/racingcar/View.java
> +        String rawUserInput = Console.readLine();
입출력만을 담당하는 클래스 `Input`과 `Output`을 생성하였습니다!

2022-03-26 10:42 UTC, kth496 commented on src/main/java/racingcar/View.java
> +    private static Consumer<Object> printFunction = x -> System.out.print(x);
@Hepheir 넵 확인해보니 이 부분은 말씀하신대로 매번 PrintStream을 새로 생성하는 상황이라 문제가 되었네요. 메서드 참조는 해당 시점을 캡쳐하기 때문에 변화된 PrintStream으로 출력되지 않은 것으로 확인됩니다. 디테일하게 챙겨주셨네요 👍

2022-03-28 11:58 UTC, closed without merging